add redux and contact interactions
RushanCources/InteractionHistory pull request #14
Opened 2021-07-25 21:02 UTC by SherstnevVasiliy

2021-07-26 06:51 UTC, coolsoftrf requested changes

2021-07-26 06:51 UTC, coolsoftrf commented on interactio-history-rn/src/components/ContactInteractionsTab/ContactInteractionsTab.tsx
> +        <Text>{`data: ${item.item.date}`}</Text>
это не данные, это дата
и переименуй также остальные строчки в UI - это описания полей, а не их названия в БД

2021-07-26 06:51 UTC, coolsoftrf commented on interactio-history-rn/src/components/ContactInteractionsTab/ContactInteractionsTab.tsx
> +      {response && <FlatList data={response} renderItem={renederItem}/>}
обработай случай когда ответ от сервера приходит не мгновенно

2021-07-26 06:51 UTC, coolsoftrf commented on interactio-history-rn/src/components/ContactInteractionsTab/ContactInteractionsTab.tsx
> +const styles = StyleSheet.create({
общие стили Георгий вынес в отдельный файл - по возможности использу их, а свои стили добавляй в компоненты только в специфических кейсах

2021-07-26 06:51 UTC, coolsoftrf commented on interactio-history-rn/src/navigation/ContactInformationScreen/ContactInformationScreen.tsx
> +export default ContactInformationScreen;
автопьюрифаер?

2021-07-26 06:51 UTC, coolsoftrf commented on interactio-history-rn/src/navigation/NavigationStack/NavigationStack.tsx
> +export default NavigationStack;
автопьюрифаер?

2021-07-26 06:51 UTC, coolsoftrf commented on interactio-history-rn/src/styles.global.ts
> -    fontSize: 24,
?

2021-07-26 06:51 UTC, coolsoftrf commented on interactio-history-rn/src/styles.global.ts
> -    textAlign: 'center',
?

2021-07-26 06:51 UTC, coolsoftrf commented on interactio-history-rn/src/store/slice.ts
> +      .then(result => result);
?

2021-07-26 06:51 UTC, coolsoftrf commented on interactio-history-rn/src/store/slice.ts
> +    });
если перед этим успехом в стейте лежала ошибка, она там и останется?

2021-07-27 21:58 UTC, SherstnevVasiliy commented on interactio-history-rn/src/components/ContactInteractionsTab/ContactInteractionsTab.tsx
> +        <Text>{`data: ${item.item.date}`}</Text>
все переделал

2021-07-27 21:58 UTC, SherstnevVasiliy commented on interactio-history-rn/src/components/ContactInteractionsTab/ContactInteractionsTab.tsx
> +      {response && <FlatList data={response} renderItem={renederItem}/>}
обработал

2021-07-27 21:58 UTC, SherstnevVasiliy commented on interactio-history-rn/src/components/ContactInteractionsTab/ContactInteractionsTab.tsx
> +const styles = StyleSheet.create({
применил

2021-07-27 21:59 UTC, SherstnevVasiliy commented on interactio-history-rn/src/store/slice.ts
> +    });
уже нет

2021-07-28 13:08 UTC, SherstnevVasiliy commented on interactio-history-rn/src/store/slice.ts
> +      .then(result => result);
пофикшу вечером

2021-07-28 13:08 UTC, SherstnevVasiliy commented on interactio-history-rn/src/styles.global.ts
> -    textAlign: 'center',
видимо преттиер глючил

2021-07-28 13:09 UTC, SherstnevVasiliy commented on interactio-history-rn/src/styles.global.ts
> -    fontSize: 24,
видимо преттиер глючил

2021-07-28 13:09 UTC, SherstnevVasiliy commented on interactio-history-rn/src/navigation/NavigationStack/NavigationStack.tsx
> +export default NavigationStack;
видимо преттиер глючил

2021-07-28 13:09 UTC, SherstnevVasiliy commented on interactio-history-rn/src/navigation/ContactInformationScreen/ContactInformationScreen.tsx
> +export default ContactInformationScreen;
видимо преттиер глючил

2021-07-28 14:35 UTC, coolsoftrf commented on interactio-history-rn/src/styles.global.ts
> -    fontSize: 24,
Нет, просто удалилась половина стилей при мерже. Теперь в коде ошибки лезут из-за не найденных стилей
![image](https://user-images.githubusercontent.com/22420601/127341418-8b86ce47-810d-4275-8870-e3d64b7e2fd3.png)

2021-07-28 14:48 UTC, coolsoftrf requested changes

2021-07-28 14:48 UTC, coolsoftrf commented on interactio-history-rn/src/store/type.ts
> +export type Tresponse = {
Что-то с ТКэмелКейсом не то - поправь плиз

2021-07-28 14:48 UTC, coolsoftrf commented on interactio-history-rn/src/store/type.ts
> +export type TresponseProps = {
снова ТКэмелКейс

2021-07-28 15:39 UTC, coolsoftrf approved these changes
осталось 2 коммента с кэмелкейсом. Поправь их отдельным реквестом плиз

2021-07-28 15:41 UTC, merged