create add navigation
RushanCources/InteractionHistory pull request #8
Opened 2021-07-14 20:03 UTC by GeorgiyCox

2021-07-16 12:05 UTC, coolsoftrf requested changes

2021-07-16 12:05 UTC, coolsoftrf commented on interactio-history-rn/src/components/ContactInteractions/ContactInteractions.tsx
> +  sectionTitle: {
лучше вытащи общие стили в отдельный файл (в дальнейшем в качестве допчика сделаем темы), а в компонентах используй уже эти константы

2021-07-16 12:05 UTC, coolsoftrf commented on interactio-history-rn/src/components/ContactDetails/ContactDetails.tsx
> +const ContactDetails = () => {
Для улучшения читабельности переименуй лучше все табы в что-то содержащее Tab (в случае с делаталями - ContactDetailsTab, например), а табовый навигатор - во что-то без Tab (например, ContactScreen), ибо там кроме самого навигатора ещё и другие комопоненты могут находиться,

2021-07-16 17:26 UTC, GeorgiyCox commented on interactio-history-rn/src/components/ContactInteractions/ContactInteractions.tsx
> +  sectionTitle: {
исправил

2021-07-16 17:26 UTC, GeorgiyCox commented on interactio-history-rn/src/components/ContactDetails/ContactDetails.tsx
> +const ContactDetails = () => {
исправил

2021-07-17 08:10 UTC, coolsoftrf commented on interactio-history-rn/src/components/ContactDetails/ContactDetails.tsx
> +const ContactDetails = () => {
имена компонентов тоже)

2021-07-17 15:22 UTC, GeorgiyCox commented on interactio-history-rn/src/components/ContactDetails/ContactDetails.tsx
> +const ContactDetails = () => {
исправил

2021-07-18 00:26 UTC, coolsoftrf approved these changes

2021-07-18 00:26 UTC, coolsoftrf commented on interactio-history-rn/src/navigation/NavigationScreen/ContactScreen.tsx
> +const ContactScreen = () => {
этот компонент ещё где-то используется? если нет - удаляй

2021-07-18 00:26 UTC, merged