App contacts and contact details
RushanCources/InteractionHistory pull request #9
Opened 2021-07-17 15:22 UTC by GeorgiyCox

2021-07-20 10:45 UTC, coolsoftrf requested changes

2021-07-20 10:45 UTC, coolsoftrf commented on interactio-history-rn/src/components/ContactDetailsTab/ContactDetailsTab.tsx
> +        dataContact.work &&
skype

2021-07-20 10:45 UTC, coolsoftrf commented on interactio-history-rn/src/navigation/ContactDetailsTitleNav/ContactDetailsTitleNav.tsx
> +				{dataContact.jobTitle} at {dataContact.account?.name}
Ты предполагаешь, что аккаунта может не быть, тогда вопрос - какой результат мы получим на эране если аккаунта таки не будет? Аналогично в ContactDetailsTitleNav.

2021-07-20 11:55 UTC, GeorgiyCox commented on interactio-history-rn/src/navigation/ContactDetailsTitleNav/ContactDetailsTitleNav.tsx
> +				{dataContact.jobTitle} at {dataContact.account?.name}
Это не я, а ts. Но все таки стоит проработать этот вариант?И анологично в чем? Указал этот же файл.

2021-07-21 13:01 UTC, GeorgiyCox commented on interactio-history-rn/src/components/ContactDetailsTab/ContactDetailsTab.tsx
> +        dataContact.work &&
исправил

2021-07-21 13:01 UTC, GeorgiyCox commented on interactio-history-rn/src/navigation/ContactDetailsTitleNav/ContactDetailsTitleNav.tsx
> +				{dataContact.jobTitle} at {dataContact.account?.name}
исправил

2021-07-24 07:30 UTC, coolsoftrf requested changes

2021-07-24 07:30 UTC, coolsoftrf commented on interactio-history-rn/.vscode/settings.json
> +{
добавь .vscode в .gitignore и не коммить локальные настройки

2021-07-24 07:30 UTC, coolsoftrf commented on interactio-history-rn/src/components/common/ContactNameBlock/ContactNameBlock.tsx
> +            jobTitle && <Text style={styleTitle}>{firstName + ' '}</Text>
что-то тут не то с логикой

2021-07-24 07:52 UTC, GeorgiyCox commented on interactio-history-rn/src/components/common/ContactNameBlock/ContactNameBlock.tsx
> +            jobTitle && <Text style={styleTitle}>{firstName + ' '}</Text>
исправил

2021-07-24 07:57 UTC, GeorgiyCox commented on interactio-history-rn/.vscode/settings.json
> +{
исправил

2021-07-24 15:30 UTC, closed without merging